__target__: EnhancedVelocityModule
# Multi-scale neighbor lists for different feature scales
frame_knn_list: [32, 40, 48]
num_train_points: 512
# Feature dimensions
feat_embedding_dim: 672
decoder_hidden_dim: 168
dsm_sigma: 0.01
